---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Creating Internet Gateway and Route Table"

Parameters:
  NetworkStack:
    Type: "String"
    Description: "Creating Networking Stack for Resources"

Resources:

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: !Ref AWS::StackName

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId:
        Fn::ImportValue:              
          !Sub ${NetworkStack}-VpcId 


  publicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Fn::ImportValue:
          !Sub ${NetworkStack}-VpcId
      Tags:
      - Key: Name
        Value: vpc-dr-public-route-table


 
  publicRouteToInternet:
    DependsOn: InternetGatewayAttachment
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0 
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref publicRouteTable


  publicRouteTableAssociationA:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref publicRouteTable
      SubnetId:
        Fn::ImportValue:
          !Sub ${NetworkStack}-PublicsubnetA
